apiVersion: v1
kind: Service
metadata:
  name: kube-dns-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.200.25
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53