apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-admin
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev