apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-view
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: ken
  namespace: dev