apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: web
spec:
  containers:
  - name: web
    image: mai200/web:1.01.0
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: init-web
    image: busybox:1.31
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}


